### ISSUE TITLE
Cannot set property 'socketId' of undefined

### ISSUE THREAD

**Issue by poxin13** [tlaverdure/laravel-echo-server#124]
Apologies if this an issue for Echo and not this repository.

I'm attempting a simple demo of working with redis/socket.io with a presence channel using the latest version of Laravel 5.4 with Vue.

I have a simple channel defined as:
```
Broadcast::channel('chat', function ($user) {
    return [
        'id' => $user->id,
        'name' => $user->name
    ];
});
```

Then in my vue file:
```
mounted() {
    Echo.join(`chat`)
        .here((users) => {
            console.log(users);
        })
        .joining((user) => {
            console.log(user.name);
        })
        .leaving((user) => {
            console.log(user.name);
        });
}
```

I see the key being created in redis, however in the laravel-echo-server terminal I am getting the error:
```
[1:08:07 AM] - ZRyZ2AiHjX8nZMLVAAAC authenticated for: presence-chat
[1:08:07 AM] - ZRyZ2AiHjX8nZMLVAAAC joined channel: presence-chat
(node:12234) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot set property 'socketId' of undefined
```

I'm a little stumped what to look for. socketId always seems to be 'undefined'.

**Comment by xem1** [comment]
Have same problem after update. Users in channel dont count.
laravel-echo-server 1.2.5
laravel-echo 1.2.4
Request header going usually `X-Socket-Id:VtMMhbiZn0FIWPQMAAAB`
And request going to socket server is `sid:VtMMhbiZn0FIWPQMAAAB`

**Comment by poxin13** [comment]
Closing this, opened at laravel/echo [https://github.com/laravel/echo/issues/99](url)

**Comment by barryvdh** [comment]
Redis/sqlite is working properly?

**Comment by poxin13** [comment]
Yeah Redis is setup okay and connects just fine

**Comment by poxin13** [comment]
At mentioned by @filipegar on the laravel/echo side, pulling back laravel-echo-server to 1.2.4 fixes the issue.

**Comment by filipegar** [comment]
I think it has something to do with ec4277a
I'm currently trying a few things here. if i manage to get it working again, i'll open a pull request.

**Comment by barryvdh** [comment]
What is the raw value of `response.body` before parsing?

**Comment by tlaverdure** [comment]
Thanks for catching that. Should be fixed now with https://github.com/tlaverdure/laravel-echo-server/commit/fab1333f6483f719d34026f52dedf625d624ec1c

**Comment by ty666** [comment]
why my laravel-echo-server  still this problems?
laravel-echo-server 1.2.7
thinks.

**Comment by tinpont** [comment]
I'm using laravel-echo-server 1.2.7, seems still have this problem.

```
L A R A V E L  E C H O  S E R V E R

version 1.2.7

⚠ Starting server in DEV mode...

✔  Running at localhost on port 8230
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[9:19:02 AM] - gKKTD8vDXMGPSmCiAAAB authenticated for: presence-chat.1
[9:19:03 AM] - gKKTD8vDXMGPSmCiAAAB joined channel: presence-chat.1
(node:4056) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot set property 'socketId' of undefined
```

**Comment by MyMediaMagnet** [comment]
This is happening for me on 1.2.5, 1.2.6 & 1.2.7.  Oddly, it's only happening on my digital ocean server and not on my local.  1.2.4 didn't work for me either, but the error was different this time.  Any suggestions for me?

**Comment by luchaos** [comment]
this is still happening in 1.2.8
https://github.com/tlaverdure/laravel-echo-server/issues/169

**Comment by KyleMassacre** [comment]
I found that if listening to an incorrect event this error was triggering

**Comment by v-Stein** [comment]
Still happens with `laravel-echo-server@1.2.9` and `laravel-echo@1.3.0`.
I checked but all events I am listening are correct ones and do trigger themselves, though the error is shwing in the server CLI

**Comment by skatetdieu** [comment]
For anyone else running into this, I figured out the issue and comment the solution on this here:
https://github.com/tlaverdure/laravel-echo-server/issues/202#issuecomment-323249811
