### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined when connecting to private channel

### ISSUE THREAD

**Issue by exzib** [tlaverdure/laravel-echo-server#209]
Whenever someone joins a private channel the whole echo server just shuts down because of an error stating:
```
url.js:81
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at PrivateChannel.authHost (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:21:27)
    at PrivateChannel.authenticate (/usr/lib/node_modules/laravel-echo-server/dist/channels/private-channel.js:13:23)
    at Channel.joinPrivate (/usr/lib/node_modules/laravel-echo-server/dist/channels/channel.js:60:22)
    at Channel.join (/usr/lib/node_modules/laravel-echo-server/dist/channels/channel.js:19:22)
    at Socket.<anonymous> (/usr/lib/node_modules/laravel-echo-server/dist/echo-server.js:112:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /usr/lib/node_modules/laravel-echo-server/node_modules/socket.io/lib/socket.js:514:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

Why is there no try for this? What is actually going on here? Nothing helps because whenever I start server this error comes up and server crashes so no way of debugging.

What is the cause here? What is actually wrong?

Here is my laravel echo server json file:

```
{
	"appKey": "base64:3G5RJ0OYWYu1Bd47FlXgX1kZgzHJl6wkEswK2CWKfd4=",
	"authHost": "https://altpocket.io",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "4b42a4ac276318dc",
			"key": "ddd5816d7fe7ad10c6d9f78dcbacd136"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "localhost"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"port": "6002",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/etc/nginx/ssl/Altpocket.io/203319/server.crt",
	"sslKeyPath": "/etc/nginx/ssl/Altpocket.io/203319/server.key"
}
```

I use custom authentication at /broadcasting/auth:

`Route::post('/broadcasting/auth', 'PusherController@auth');`

```
  public function auth(Request $request)
  {
    return 1;
  }
```

How the code looks when connecting to channels, connecting to channels works fine and so does receiving notifications until the bug comes up, it seems like there is no socket referral getting sent back and I have no idea how to do this?

```
@extends('layouts.master')

@section('content')
  <ul id="messages"></ul>
  <form action="">
    <input id="m" autocomplete="off" /><button>Send</button>
  </form>
@stop

@section('footer')
<script src="{{ elixir('js/6001-9.js') }}"></script>
<script>
Echo.channel('test-channel')
    .listen(".Notification", (event) => {
    console.log(event);
});
Echo.channel('announcements')
    .listen(".Notification", (event) => {
    console.log(event);
});

Echo.private('App.User.{{Auth::user()->id}}')
.listen(".Illuminate\\Notifications\\Events\\BroadcastNotificationCreated", (event) => {
  toastr.options = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": false,
    "positionClass": "toast-bottom-right",
    "preventDuplicates": false,
    "onclick": null,
    "showDuration": "0",
    "hideDuration": "0",
    "timeOut": "0",
    "extendedTimeOut": "0",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  }
    Command: toastr[event.category](event.value)

    if(event.value == "Your import is complete! Go to your investments to see your import" && window.location.pathname == "/investments")
    {
      location.reload();
    }
    if(event.value == "Your import is complete! Go to your investments to see your import" && window.location.pathname == "/investments/")
    {
      location.reload();
    }
        });

</script>
@stop
```

**Comment by exzib** [comment]
```
    PrivateChannel.prototype.authHost = function (socket) {
        var referer = url.parse(socket.request.headers.referer);
        var authHostSelected = 'http://localhost';
        var authHosts = (this.options.authHost) ?
            this.options.authHost : this.options.host;
        if (typeof authHosts === "string") {
            authHosts = [authHosts];
        }
        for (var _i = 0, authHosts_1 = authHosts; _i < authHosts_1.length; _i++) {
            var authHost = authHosts_1[_i];
            authHostSelected = authHost;
            if (this.hasMatchingHost(referer, authHost)) {
                authHostSelected = referer.protocol + "//" + referer.host;
                break;
            }
        }
        ;
```

Here is where the error comes from this line to be specific:
`        var referer = url.parse(socket.request.headers.referer);`

**Comment by tlaverdure** [comment]
https://github.com/tlaverdure/laravel-echo-server/pull/203 should fix. Planning on a new release today.

**Comment by tlaverdure** [comment]
Should be fixed now, please try 1.3.1

**Comment by exzib** [comment]
@tlaverdure I just reinstalled laravel-echo-server to 1.3.1 but it still happens.

How do I know I properly updated it or the version? 
I did npm uninstall laravel-echo-server and then npm install laravel-echo-server@1.3.1

Still happens for me.

http://i.imgur.com/CSNgKx7.png

http://i.imgur.com/7TEfxgd.png

I went to /usr/lib/node_modules/laravel-echo-server and none of the files are updated.

**Comment by exzib** [comment]
@tlaverdure I just ran the command and it said version 1.3.0 how do I reinstall the new version?

**Comment by tlaverdure** [comment]
You can try this https://docs.npmjs.com/getting-started/updating-global-packages or uninstalling and then reinstalling

npm install laravel-echo-server@1.3.1 -g

**Comment by exzib** [comment]
Just reinstalled and it seems to be working fine now, thanks, I'll report any issues.
