### ISSUE TITLE
Broadcast Notifications Not working

### ISSUE THREAD

**Issue by diadal** [tlaverdure/laravel-echo-server#300]
my console.log empty after fired Notification `database & mail` working but `broadcast` not have tired different method still not working

```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
// use Illuminate\Notifications\Messages\BroadcastMessage;

class AccessPin extends Notification implements ShouldQueue
{
    use Queueable;

    protected $user;
    protected $pin;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($user,$pin)
    {
        $this->user = $user;
        $this->pin = $pin;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['database','broadcast'];
        // return ['mail','database','broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        
        // return (new MailMessage)
        //                     ->subject('New Access Pin')
        //                     ->markdown('emails.pin', ['user'=> $this->user,'pin'=> $this->pin]);
    }

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [

            'sub' => 'New Access Pin',
            'user' => $this->user,
           
        ];
    }

    // public function toBroadcast($notifiable)
    // {
    //     // return new BroadcastMessage([
    //     // 'sub' => 'New Access Pin',
    //     // ]);
    //     $data = ['sub' => 'New Access Pin'];
    //     return (new BroadcastMessage($data));
    // }

}


```

My js for socket.io
```
var userId= "{{ strtoupper(Auth::id()) }}";

Echo.private('App.User.' + userId)
    .notification((notification) => {
        console.log('Yee');
        console.log(notification);
    });

```
Redis

```
[2018-05-23 20:49:07][5920] Processing: Illuminate\Notifications\Events\BroadcastNotificationCreated
[2018-05-23 20:49:07][5920] Processed:  Illuminate\Notifications\Events\BroadcastNotificationCreated

```

after fired notification 

`Channel: private-users.1E938F11-3434-4780-93E2-6996782136EA
Event: Illuminate\Notifications\Events\BroadcastNotificationCreated
CHANNEL private-users.1E938F11-3434-4780-93E2-6996782136EA`

**Comment by diadal** [comment]
if any having the same issue the solution is too simple but took almost 10 hours to fix 

`'App.User.'` must be  `=` to `public function receivesBroadcastNotificationsOn()
    {
        return 'users.'.$this->id;
    }` in your users model  

wrong 
```
var userId= "{{ Auth::id() }}";

Echo.private('App.User.' + userId)
    .notification((notification) => {
        console.log('Yee');
        console.log(notification);
    });

```

Right

```
var userId= "{{ Auth::id() }}";

Echo.private('users.' + userId)
    .notification((notification) => {
        console.log('Yee');
        console.log(notification);
    });

```

don't forget to update same @ channel route

```
Broadcast::channel('users.{id}', function ($user, $id) {

    return (int) $user->id === (int) $id;
    
});

```

**Comment by bgarrison25** [comment]
Actually, I am having this same issue and both my function and the channel match....they are both using App.User.{id} and it should be working but i get a "no query results" error on broadcast. Only after updating laravel.

**Comment by tiriwo** [comment]
@diadal , i still have the same issue, despite implementing your solution

**Comment by diadal** [comment]
share your code

**Comment by haythembenkhlifa** [comment]
Laravel 5.8 the same issue

**Comment by carlos-cruz** [comment]
You should also check your **failed_jobs** table for any hints.. For some reason I found out that no exceptions are thrown when an error occurs broadcasting a notification. And I found my solution on this table records.
